### ISSUE TITLE
optacloud project solver config not up2date with latest optaplanner?

### ISSUE THREAD

**Issue by jhrcek** [kiegroup/kie-wb-playground#14]
When building solver using
```
SolverFactory.createFromKieContainerXmlResource(
                kieContainer, "optacloud/optacloud/cloudSolverConfig.solver.xml");
```

I'm getting the following exception

```
java.lang.IllegalStateException: The solutionClass (class optacloud.optacloud.CloudSolution) has a PlanningScore annotated member (bean property score on class org.optaplanner.core.impl.domain.solution.AbstractSolution) but the solver configuration still has a deprecated scoreDefinitionType or scoreDefinitionClass element.
Maybe remove the <scoreDefinitionType>, <bendableHardLevelsSize>, <bendableSoftLevelsSize> and <scoreDefinitionClass> elements from the solver configuration.
	at org.optaplanner.core.impl.domain.solution.descriptor.SolutionDescriptor.processScoreAnnotation(SolutionDescriptor.java:397)
	at org.optaplanner.core.impl.domain.solution.descriptor.SolutionDescriptor.processAnnotations(SolutionDescriptor.java:197)
	at org.optaplanner.core.impl.domain.solution.descriptor.SolutionDescriptor.buildSolutionDescriptor(SolutionDescriptor.java:112)
	at org.optaplanner.core.config.domain.ScanAnnotatedClassesConfig.buildSolutionDescriptor(ScanAnnotatedClassesConfig.java:87)
	at org.optaplanner.core.config.solver.SolverConfig.buildSolutionDescriptor(SolverConfig.java:270)
	at org.optaplanner.core.config.solver.SolverConfig.buildSolver(SolverConfig.java:216)
	at org.optaplanner.core.impl.solver.AbstractSolverFactory.buildSolver(AbstractSolverFactory.java:57)
```
could you please update the [solver config](https://github.com/kiegroup/kie-wb-playground/blob/master/optacloud/src/main/resources/optacloud/optacloud/cloudSolverConfig.solver.xml) file so that this error disappears?

**Comment by mcimbora** [comment]
@jhrcek Thanks for pointing this out, there's already a pending PR to resolve the problem.

**Comment by mcimbora** [comment]
https://github.com/kiegroup/kie-wb-playground/pull/10

**Comment by ge0ffrey** [comment]
None of the other repo's have an issues tab, as we standarize on jira, so I am removing the issues tab here.
Issues should go in: https://issues.jboss.org/projects/PLANNER (DROOLS, JBPM, etc)

Regardless, thanks for reporting this issue. It looks like its fixed already, so this one is fine.
